package com.emerchantpay.gateway.genesisandroid.api.models

import java.util.*

class Country {

    // Get ISO code
    var code: String = ""
    var countryName: String = ""

    // Get Country names list
    val countryNames: ArrayList<String>
        get() = countryNamesList

    constructor() : super() {}

    constructor(code: String, name: String) {

        this.code = code
        this.countryName = name
        countriesMap[name] = code
        countryNamesList.add(name)
    }

    // Get ISO code
    fun getIsoCode(name: String): String? {
        return countriesMap[name]
    }

    fun getCountry(country: String): Country? {
        val countryCode = countriesMap[country]

        return countryCode?.let { Country(it, country) }
    }

    companion object {

        private val countriesMap = HashMap<String, String>()
        private val countryNamesList = ArrayList<String>()

        var Afganistan = Country("AF", "Afghanistan")
        var AlandIsland = Country("AX", "Aland Islands")
        var Albania = Country("AL", "Albania")
        var Algeria = Country("DZ", "Algeria")
        var AmericanSamoa = Country("AF", "American Samoa")
        var Andorra = Country("AD", "Andorra")
        var Angola = Country("AO", "Angola")
        var Anguilla = Country("AI", "Anguilla")
        var Antarctica = Country("AQ", "Antarctica")
        var Antiqua = Country("AG", "Antiqua And Barbuda")
        var Argentina = Country("AR", "Argentina")
        var Armenia = Country("AM", "Armenia")
        var Aruba = Country("AW", "Andorra")
        var Australia = Country("AU", "Australia")
        var Austria = Country("AT", "Austria")
        var Azerbaijan = Country("AZ", "Azerbaijan")
        var Bahamas = Country("BS", "Bahamas")
        var Bahrain = Country("BH", "Bahrain")
        var Bangladesh = Country("BD", "Bangladesh")
        var Barbados = Country("BB", "Barbados")
        var Belarus = Country("BY", "Belarus")
        var Belgium = Country("BE", "Belgium")
        var Belize = Country("BZ", "Belize")
        var Benin = Country("BJ", "Benin")
        var Bermuda = Country("BM", "Bermuda")
        var Bhutan = Country("BT", "Bhutan")
        var Bolivia = Country("BO", "Bolivia")
        var BosniaAndHerzegovina = Country("BA", "Bosnia And Herzegovina")
        var Botswana = Country("BW", "Botswana")
        var BouwetIsland = Country("BV", "Bouwet Island")
        var Brazil = Country("BR", "Brazil")
        var BritishIndianOceanTerritory = Country("IO", "British Indian Ocean Territory")
        var Brunei = Country("BN", "Brunei Darussalam")
        var Bulgaria = Country("BG", "Bulgaria")
        var BurcinaFaso = Country("BF", "Burcina Faso")
        var Burundi = Country("BI", "Burundi")
        var Cambodia = Country("KH", "Cambodia")
        var Cameroon = Country("CM", "Cameroon")
        var Canada = Country("CA", "Canada")
        var CapeVerde = Country("CV", "Cape Verde")
        var CaymanIslands = Country("KY", "Cayman Islands")
        var CentralAfricanRepublic = Country("CF", "Central African Republic")
        var Chad = Country("TD", "Chad")
        var Chile = Country("CL", "Chile")
        var China = Country("CN", "China")
        var ChristmasIsland = Country("CX", "Christmas Island")
        var CocosIslands = Country("CC", "Cocos (Keeling) Islands")
        var Colombia = Country("CO", "Colombia")
        var Comoros = Country("KM", "Comoros")
        var Congo = Country("CG", "Congo")
        var CongoDemocraticRepublic = Country("CD", "Congo Democratic Republic")
        var CookIslands = Country("CK", "Cook Islands")
        var CostaRica = Country("CR", "Costa Rica")
        var CoteDIvoire = Country("CI", "Cote D\'Ivoire")
        var Croatia = Country("HR", "Croatia")
        var Cuba = Country("CU", "Cuba")
        var Cyprus = Country("CY", "Cyprus")
        var CzechRepublic = Country("CZ", "Czech Republic")
        var Denmark = Country("DK", "Denmark")
        var Djibuti = Country("DJ", "Djibuti")
        var Dominica = Country("DM", "Dominica")
        var DominicanRepublic = Country("DO", "Dominican Republic")
        var Ecuador = Country("EC", "Ecuador")
        var Egypt = Country("EG", "Egypt")
        var ElSalvador = Country("SV", "El Salvador")
        var EquatorialGuinea = Country("GQ", "Equatorial Guinea")
        var Erithrea = Country("ER", "Erithrea")
        var Estonia = Country("EE", "Estonia")
        var Ethiopia = Country("ET", "Ethiopia")
        var FalklandIslands = Country("FK", "Falkland Islands (Malvinas)")
        var FaroeIslands = Country("FO", "Faroe Islands")
        var Fiji = Country("FJ", "Fiji")
        var Finland = Country("FI", "Finland")
        var France = Country("FR", "France")
        var FrenchGuiana = Country("GF", "French Guiana")
        var FrenchPolynesia = Country("PF", "French Polynesia")
        var FrenchSouthernTerritories = Country("TF", "French Southern Territories")
        var Gabon = Country("GA", "Gabon")
        var Gambia = Country("GM", "Gambia")
        var Georgia = Country("GE", "Georgia")
        val Germany = Country("DE", "Germany")
        var Ghana = Country("GH", "Gabon")
        var Gibraltar = Country("GI", "Gibraltar")
        var Greece = Country("GR", "Greece")
        var Greenland = Country("GL", "Greenland")
        var Grenada = Country("GD", "Grenada")
        var Guadeloupe = Country("GP", "Guadeloupe")
        var Guam = Country("GU", "Guam")
        var Guatemala = Country("GT", "Guatemala")
        var Guernsey = Country("GG", "Guernsey")
        var Guinea = Country("GN", "Guinea")
        var GuineaBissau = Country("GW", "Guiunea-Bissau")
        var Guyana = Country("GY", "Guyana")
        var Haiti = Country("HT", "Haiti")
        var HeardIslandandMcdonalIslands = Country("HM", "Heard Island & Mcdonald Islands")
        var VaticanCity = Country("VA", "Holy See (Vatican City State)")
        var Honduras = Country("'HN", "Honduras")
        var HongKong = Country("HK", "Hong Kong")
        var Hungary = Country("HU", "Hungary")
        var Iceland = Country("IS", "Iceland")
        var India = Country("IN", "India")
        var Iran = Country("IR", "Iran, Islamic Republic Of")
        var Iraq = Country("IQ", "Iraq")
        var Ireland = Country("IE", "Ireland")
        var IsleOfMan = Country("IM", "Isle of Man")
        var Israel = Country("IL", "Israel")
        var Italy = Country("IT", "Italy")
        var Jamaica = Country("JM", "Jamaica")
        var Japan = Country("JP", "Japan")
        var Jersey = Country("JE", "Jersey")
        var Kazakhstan = Country("KZ", "Kazakhstan")
        var Kenya = Country("KE", "Kenya")
        var Kiribati = Country("KI", "Kiribati")
        var Korea = Country("KR", "Korea")
        var Kuweit = Country("KW", "Kuwait")
        var Kyrgyzstan = Country("KG", "Kyrgyzstan")
        var LaoPeopleDemocraticRepublic = Country("LA", "Lao People\'s Democratic Republic")
        var Latvia = Country("LV", "Latvia")
        var Lebanon = Country("LB", "Lebanon")
        var Lesotho = Country("LS", "Lesotho")
        var Liberia = Country("LR", "Liberia")
        var Libya = Country("LY", "Libyan Arab Jamahiriya")
        var Liechtenstein = Country("LI", "Liechtenstein")
        var Luxembourg = Country("LU", "Luxembourg")
        var Macao = Country("MO", "Macao")
        var Macedonia = Country("MK", "Macedonia")
        var Madagascar = Country("MG", "Madagascar")
        var Malawi = Country("MW", "Malawi")
        var Malaysia = Country("MY", "Malaysia")
        var Maldives = Country("MV", "Maldives")
        var Mali = Country("ML", "Mali")
        var Malta = Country("MT", "Malta")
        var MarshallIslands = Country("MH", "Marshall Islands")
        var Martinique = Country("MQ", "Martinique")
        var Mauritania = Country("MR", "Mauritania")
        var Mairitius = Country("MU", "Mauritius")
        var Mayotte = Country("YT", "Mayotte")
        var Mexico = Country("MX", "Mexico")
        var Micronesia = Country("FM", "Micronesia, Federated States Of")
        var Moldova = Country("MD", "Moldova")
        var Monaco = Country("MC", "Monaco")
        var Mongolia = Country("MN", "Mongolia")
        var Montenegro = Country("ME", "Montenegro")
        var Montserrat = Country("MS", "Montserrat")
        var Marocco = Country("MA", "Marocco")
        var Mozambique = Country("MZ", "Mozambique")
        var Myanmar = Country("MM", "Myanmar")
        var Namibia = Country("NA", "Namibia")
        var Nauru = Country("NR", "Nauru")
        var Nepal = Country("NP", "Nepal")
        var Netherlands = Country("NL", "Netherlands")
        var NetherlandsAntilles = Country("AN", "Netherlands Antilles")
        var NewCaledonia = Country("NC", "New Caledonia")
        var NewZealand = Country("NZ", "New Zealand")
        var Nicaragua = Country("NI", "Nicaragua")
        var Niger = Country("NE", "Niger")
        var Nigeria = Country("NG", "Nigeria")
        var Niue = Country("NU", "Niue")
        var NorfolkIsland = Country("NF", "Norfolk Island")
        var NorthernMarianaIslands = Country("MP", "Northern Mariana Islands")
        var Norway = Country("NO", "Norway")
        var Oman = Country("OM", "Oman")
        var Pakistan = Country("PK", "Pakistan")
        var Palau = Country("PW", "Palau")
        var PalestinianTerritory = Country("PS", "Palestinian Territory, Occupied")
        var Panama = Country("PA", "Panama")
        var PapuaNewGuinea = Country("PG", "Papua New Guinea")
        var Peru = Country("PE", "Peru")
        var Philippines = Country("PH", "Philippines")
        var Pitcairn = Country("PN", "Pitcairn")
        var Poland = Country("PL", "Poland")
        var Portugal = Country("PT", "Portugal")
        var PuertoRico = Country("PR", "Puerto Rico")
        var Qatar = Country("QA", "Qatar")
        var Reunion = Country("RE", "Reunion")
        var Romania = Country("RO", "Romania")
        var Russia = Country("RU", "Russian Federation")
        var Rwanda = Country("RW", "Rwanda")
        var SaintBarthelemy = Country("BL", "Saint Barthelemy")
        var SaintHelena = Country("SH", "Saint Helena")
        var SaintKittsAndNevis = Country("KN", "Saint Kitts And Nevis")
        var SaintLucia = Country("LC", "Saint Lucia")
        var SaintMartin = Country("MF", "Saint Martin")
        var SaintPierreAndMiquelon = Country("PM", "Saint Pierre And Miquelon")
        var SaintVincentAndGrenadines = Country("VC", "Saint Vincent And Grenadines")
        var Samoa = Country("WS", "Samoa")
        var SanMarino = Country("SM", "San Marino")
        var SaoTomeAndPrincipe = Country("ST", "Sao Tome And Principe")
        var SaudiArabia = Country("SA", "Saudi Arabia")
        var Senegal = Country("SN", "Senegal")
        var Serbia = Country("RS", "Serbia")
        var Seychelles = Country("SC", "Seychelles")
        var SierraLeone = Country("SL", "Sierra Leone")
        var Singapore = Country("SG", "Singapore")
        var Slovakia = Country("SK", "Slovakia")
        var Slovenia = Country("SI", "Slovenia")
        var SolomonIslands = Country("SB", "SolomonIslands")
        var Somalia = Country("SO", "Somalia")
        var SouthAfrica = Country("ZA", "South Africa")
        var SouthGeorgiaAndSandwich = Country("GS", "South Georgia And Sandwich Isl.")
        var Spain = Country("ES", "Spain")
        var SriLanka = Country("LK", "Sri Lanka")
        var Sudan = Country("SD", "Sudan")
        var Suriname = Country("SR", "Suriname")
        var SvalbardAndJanMayen = Country("SJ", "Svalbard And Jan Mayen")
        var Swaziland = Country("SZ", "Swaziland")
        var Sweden = Country("SE", "Sweden")
        var Switzerland = Country("CH", "Switzerland")
        var Syria = Country("SY", "Syrian Arab Republic")
        var Taiwan = Country("TW", "Taiwan")
        var Tajikistan = Country("TJ", "Tajikistan")
        var Tanzania = Country("TZ", "Tanzania")
        var Thailand = Country("TH", "Thailand")
        var TimorLeste = Country("TL", "Timor-Leste")
        var Togo = Country("TG", "Togo")
        var Tokelau = Country("TK", "Tokelau")
        var Tonga = Country("TO", "Tonga")
        var TrinidadAndTobago = Country("TT", "Trinidad And Tobago")
        var Tunisia = Country("TN", "Tunisia")
        var Turkey = Country("TR", "Turkey")
        var Turkmenistan = Country("TM", "Turkmenistan")
        var TurksAndCaicosIslands = Country("TC", "Turks And Caicos Islands")
        var Tuvalu = Country("TV", "Tuvalu")
        var Uganda = Country("UG", "Uganda")
        var Ukraine = Country("UA", "Ukraine")
        var UnitedArabEmirates = Country("AE", "United Arab Emirates")
        var UnitedKingdom = Country("GB", "United Kingdom")
        var UnitedStates = Country("US", "United States")
        var UnitedStatesOutlyingIslands = Country("UM", "United States Outlying Islands")
        var Uruguay = Country("UY", "Uruguay")
        var Uzbekistan = Country("UZ", "Uzbekistan")
        var Vanuatu = Country("VU", "Vanuautu")
        var Venezuela = Country("VE", "Venezuela")
        var Vietnam = Country("VN", "Viet Nam")
        var VirginIslandsBritish = Country("VG", "Virgin Islands, British")
        var VirginIslandsUS = Country("VI", "'Virgin Islands, U.S.")
        var WallisAndFutuna = Country("WF", "Wallis And Futuna")
        var WesternSahara = Country("EH", "Western Sahara")
        var Yemen = Country("YE", "Yemen")
        var Zambia = Country("ZM", "Zambia")
        var Zimbabwe = Country("ZW", "Zimbabwe")
    }
}
